index:
    path: /
    controller: App\Controller\FrontController::homePage

index_contact:
    path: /contacts
    controller: App\Controller\ContactController::index

save_contact:
    path: /contact/create
    controller: App\Controller\ContactController::create

show_contact:
    path: /contact/{id}
    controller: App\Controller\ContactController::show
